{{- include "ocis.appNames" (dict "scope" . "appName" "appNameOcs" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.ocs.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["ocs", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: OCS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: OCS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: OCS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: OCS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: OCS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}

            - name: OCS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: OCS_HTTP_ADDR
              value: 0.0.0.0:9110
            - name: OCS_DEBUG_ADDR
              value: 0.0.0.0:9114

            - name: OCS_IDM_ADDRESS
            {{ if not .Values.features.externalUserManagement.enabled }}
              value: "https://{{ .Values.externalDomain }}"
            {{ else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI | quote }}
            {{ end }}

            - name: REVA_GATEWAY
              value: {{ .appNameGateway }}:9142

            - name: OCS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: OCS_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9110
            - name: metrics-debug
              containerPort: 9114
      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
