{{- include "ocis.appNames" (dict "scope" . "appName" "appNameFrontend" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.frontend.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["frontend", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: FRONTEND_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: FRONTEND_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: FRONTEND_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: FRONTEND_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: FRONTEND_HTTP_ADDR
              value: 0.0.0.0:9140
            - name: FRONTEND_DEBUG_ADDR
              value: 0.0.0.0:9141

            - name: FRONTEND_PUBLIC_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: {{ .appNameGateway }}:9142

            - name: FRONTEND_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: FRONTEND_APP_HANDLER_INSECURE
              value: {{ .Values.insecure.ocisHttpApiInsecure | quote }}

            - name: FRONTEND_ARCHIVER_INSECURE
              value: {{ .Values.insecure.ocisHttpApiInsecure | quote }}

            # cache
            - name: FRONTEND_OCS_RESOURCE_INFO_CACHE_STORE
              value: {{ .Values.cache.type | quote }}
            {{- if ne .Values.cache.type "noop" }}
            - name: FRONTEND_OCS_RESOURCE_INFO_CACHE_STORE_NODES
              value: {{ join "," .Values.cache.nodes | quote }}
            {{- end }}

            - name: FRONTEND_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

            - name: STORAGE_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.transferSecretSecretRef }}
                  key: transfer-secret

            {{- if .Values.features.quotas.max  }}
            - name: FRONTEND_MAX_QUOTA
              value: {{ .Values.features.quotas.max }}
            {{- end }}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 9140
            - name: metrics-debug
              containerPort: 9141

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
