{{- include "ocis.appNames" (dict "scope" . "appName" "appNamePostprocessing" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.postprocessing.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["postprocessing", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: POSTPROCESSING_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: POSTPROCESSING_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: POSTPROCESSING_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            # - name: POSTPROCESSING_DEBUG_PPROF
            #   value: {{ .Values.debug.profiling | quote }}

            # - name: POSTPROCESSING_DEBUG_ADDR
            #   value: 0.0.0.0:TODO

            {{- $_ := set . "postprocessingSteps" list -}}
            {{- if .Values.features.policies.enabled }}
            {{- $_ := set . "postprocessingSteps" (append .postprocessingSteps "policies") -}}
            {{- end }}
            {{- if .Values.features.virusscan.enabled }}
            {{- $_ := set . "postprocessingSteps" (append .postprocessingSteps "virusscan") -}}
            {{- end }}
            {{- if .postprocessingSteps }}
            - name: POSTPROCESSING_STEPS
              value: {{ join "," .postprocessingSteps | quote }}
            {{- end }}

            - name: POSTPROCESSING_EVENTS_ENDPOINT
            {{- if not .Values.messagingSystem.external.enabled }}
              value: {{ .appNameNats }}:9233
            {{- else }}
              value: {{ .Values.messagingSystem.external.endpoint | quote }}
            - name: POSTPROCESSING_EVENTS_CLUSTER
              value: {{ .Values.messagingSystem.external.cluster | quote }}
            - name: POSTPROCESSING_EVENTS_ENABLE_TLS
              value: {{ .Values.messagingSystem.external.tls.enabled | quote }}
            - name: POSTPROCESSING_EVENTS_TLS_INSECURE
              value: {{ .Values.messagingSystem.external.tls.insecure | quote }}
            - name: POSTPROCESSING_EVENTS_TLS_ROOT_CA_CERTIFICATE
              {{- if not .Values.messagingSystem.external.tls.certTrusted }}
              value: /etc/ocis/messaging-system-ca/messaging-system-ca.crt
              {{- else }}
              value: "" # no cert needed
              {{- end }}
            {{- end }}

          # TODO: This service does not currently provide a debug port, re-enable this once that is implemented
          # See: https://github.com/owncloud/ocis-charts/issues/111
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: metrics-debug
          #   timeoutSeconds: 10
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          #   failureThreshold: 3

          resources: {{ toYaml .resources | nindent 12 }}
          # TODO: This service does not currently provide a debug port, re-enable this once that is implemented
          # ports:
          #   - name: metrics-debug
          #     containerPort: TODO

          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: ocis-config-tmp
          emptyDir: {}
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ .Values.secretRefs.messagingSystemCaRef }}
          {{ else }}
          emptyDir: {}
          {{ end }}
