{{- if .Values.features.emailNotifications.enabled }}
{{- include "ocis.appNames" (dict "scope" . "appName" "appNameNotifications" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.notifications.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["notifications", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: NOTIFICATIONS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: NOTIFICATIONS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: NOTIFICATIONS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            # Tracing not yet implemented: https://github.com/owncloud/ocis/issues/6175
            # - name: NOTIFICATIONS_TRACING_ENABLED
            #   value: "{{ .Values.tracing.enabled }}"
            # - name: NOTIFICATIONS_TRACING_TYPE
            #   value: {{ .Values.tracing.type | quote }}
            # - name: NOTIFICATIONS_TRACING_ENDPOINT
            #   value: {{ .Values.tracing.endpoint | quote }}
            # - name: NOTIFICATIONS_TRACING_COLLECTOR
            #   value: {{ .Values.tracing.collector | quote }}

            # - name: NOTIFICATIONS_DEBUG_PPROF
            #   value: {{ .Values.debug.profiling | quote }}

            # - name: NOTIFICATIONS_DEBUG_ADDR
            #   value: 0.0.0.0:9174

            - name: NOTIFICATIONS_SMTP_HOST
              value: {{ .Values.features.emailNotifications.smtp.host | quote }}
            - name: NOTIFICATIONS_SMTP_PORT
              value: {{ .Values.features.emailNotifications.smtp.port | quote }}
            - name: NOTIFICATIONS_SMTP_SENDER
              value: {{ .Values.features.emailNotifications.smtp.sender | quote }}
            - name: NOTIFICATIONS_SMTP_AUTHENTICATION
              value: {{ .Values.features.emailNotifications.smtp.authentication | quote }}
            - name: NOTIFICATIONS_SMTP_ENCRYPTION
              value: {{ .Values.features.emailNotifications.smtp.encryption | quote }}

            - name: NOTIFICATIONS_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.notificationsSmtpSecretRef }}
                  key: smtp-username

            - name: NOTIFICATIONS_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.notificationsSmtpSecretRef }}
                  key: smtp-password

            #TODO: remove OCIS_URL in favor of NOTIFICATIONS_WEB_UI_URL
            # after https://github.com/owncloud/ocis/pull/4998 was released
            - name: OCIS_URL
              value: "https://{{ .Values.externalDomain }}"
            - name: NOTIFICATIONS_WEB_UI_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: {{ .appNameGateway }}:9142
            - name: NOTIFICATIONS_EVENTS_ENDPOINT
            {{- if not .Values.messagingSystem.external.enabled }}
              value: {{ .appNameNats }}:9233
            {{- else }}
              value: {{ .Values.messagingSystem.external.endpoint | quote }}
            - name: NOTIFICIATIONS_EVENTS_CLUSTER
              value: {{ .Values.messagingSystem.external.cluster | quote }}
            - name: NOTIFICIATIONS_EVENTS_ENABLE_TLS
              value: {{ .Values.messagingSystem.external.tls.enabled | quote }}
            - name: NOTIFICIATIONS_EVENTS_TLS_INSECURE
              value: {{ .Values.messagingSystem.external.tls.insecure | quote }}
            - name: NOTIFICIATIONS_EVENTS_TLS_ROOT_CA_CERTIFICATE
              {{- if not .Values.messagingSystem.external.tls.certTrusted }}
              value: /etc/ocis/messaging-system-ca/messaging-system-ca.crt
              {{- else }}
              value: "" # no cert needed
              {{- end }}
            {{- end }}

            - name: NOTIFICATIONS_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

          # TODO: This service does not currently provide a debug port, re-enable this once that is implemented
          # See: https://github.com/owncloud/ocis-charts/issues/111
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: metrics-debug
          #   timeoutSeconds: 10
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          #   failureThreshold: 3

          resources: {{ toYaml .resources | nindent 12 }}
          # TODO: This service does not currently provide a debug port, re-enable this once that is implemented
          # ports:
          #   - name: metrics-debug
          #     containerPort: 9174

          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: ocis-config-tmp
          emptyDir: {}
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ .Values.secretRefs.messagingSystemCaRef }}
          {{ else }}
          emptyDir: {}
          {{ end }}
{{- end }}
