{{- include "ocis.appNames" (dict "scope" . "appName" "appNameEventhistory" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.eventhistory.resources) -}}
{{- $_ := set . "store" (default (default (dict) .Values.store) .Values.services.eventhistory.store) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["eventhistory", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: EVENTHISTORY_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: EVENTHISTORY_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: EVENTHISTORY_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: EVENTHISTORY_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: EVENTHISTORY_GRPC_ADDR
              value: 0.0.0.0:8080
            # - name: EVENTHISTORY_DEBUG_ADDR
            #   value: 0.0.0.0:8081

            - name: EVENTHISTORY_STORE_TYPE
              value: {{ .store.type | quote }}
            - name: EVENTHISTORY_STORE_ADDRESSES
              value: {{ tpl (join "," .store.addresses) . | quote }}

            - name: EVENTHISTORY_EVENTS_ENDPOINT
            {{- if not .Values.messagingSystem.external.enabled }}
              value: {{ .appNameNats }}:9233
            {{- else }}
              value: {{ .Values.messagingSystem.external.endpoint | quote }}
            - name: EVENTHISTORY_EVENTS_CLUSTER
              value: {{ .Values.messagingSystem.external.cluster | quote }}
            - name: EVENTHISTORY_EVENTS_ENABLE_TLS
              value: {{ .Values.messagingSystem.external.tls.enabled | quote }}
            - name: EVENTHISTORY_EVENTS_TLS_INSECURE
              value: {{ .Values.messagingSystem.external.tls.insecure | quote }}
            - name: EVENTHISTORY_EVENTS_TLS_ROOT_CA_CERTIFICATE
              {{- if not .Values.messagingSystem.external.tls.certTrusted }}
              value: /etc/ocis/messaging-system-ca/messaging-system-ca.crt
              {{- else }}
              value: "" # no cert needed
              {{- end }}
            {{- end }}

          # TODO: This service does not currently provide a debug port, re-enable this once that is implemented
          # See: https://github.com/owncloud/ocis-charts/issues/111
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: metrics-debug
          #   timeoutSeconds: 10
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          #   failureThreshold: 3

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 8080
            # TODO: This service does not currently provide a debug port, re-enable this once that is implemented
            # - name: metrics-debug
            #   containerPort: 8081

          volumeMounts:
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: messaging-system-ca
              mountPath: /etc/ocis/messaging-system-ca
              readOnly: true

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: ocis-config-tmp
          emptyDir: {}
        - name: messaging-system-ca
          {{ if and (.Values.messagingSystem.external.enabled) (not .Values.messagingSystem.external.tls.certTrusted) }}
          secret:
            secretName: {{ .Values.secretRefs.messagingSystemCaRef }}
          {{ else }}
          emptyDir: {}
          {{ end }}
