{{- include "ocis.appNames" (dict "scope" . "appName" "appNameWebdav" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.webdav.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["webdav", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: WEBDAV_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: WEBDAV_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: WEBDAV_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: WEBDAV_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: WEBDAV_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: WEBDAV_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}

            - name: WEBDAV_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: WEBDAV_HTTP_ADDR
              value: 0.0.0.0:9115
            - name: WEBDAV_DEBUG_ADDR
              value: 0.0.0.0:9119

            - name: OCIS_PUBLIC_URL
              value: "https://{{ .Values.externalDomain }}"
            - name: REVA_GATEWAY
              value: {{ .appNameGateway }}:9142

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9115
            - name: metrics-debug
              containerPort: 9119
      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
