{{- include "ocis.appNames" (dict "scope" . "appName" "appNameWeb" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.web.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" true) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["web", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: WEB_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: WEB_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: WEB_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: WEB_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: WEB_HTTP_ADDR
              value: 0.0.0.0:9100
            - name: WEB_DEBUG_ADDR
              value: 0.0.0.0:9104

            - name: WEB_OIDC_AUTHORITY
            {{- if not .Values.features.externalUserManagement.enabled }}
              value: "https://{{ .Values.externalDomain }}"
            {{- else }}
              value: {{ .Values.features.externalUserManagement.oidc.issuerURI | quote }}
            {{- end }}

            - name: WEB_OIDC_CLIENT_ID
              value: {{ .Values.features.externalUserManagement.oidc.webClientID | quote }}

            - name: WEB_UI_THEME_SERVER
            {{- if .Values.services.web.config.theme.server }}
              value: {{ .Values.services.web.config.theme.server | quote }}
            {{- else }}
              value: https://{{ .Values.externalDomain }}
            {{- end }}
            {{- if .Values.services.web.config.theme.path }}
            - name: WEB_UI_THEME_PATH
              value: {{ .Values.services.web.config.theme.path | quote }}
            {{- end }}

            - name: WEB_UI_CONFIG_SERVER
              value: "https://{{ .Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: {{ .appNameGateway }}:9142

            - name: WEB_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 9100
            - name: metrics-debug
              containerPort: 9104

          volumeMounts:
            - name: configs
              mountPath: /etc/ocis

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: configs
          configMap:
            name: {{ .appName }}-config
