{{- include "ocis.appNames" (dict "scope" . "appName" "appNameSettings" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.settings.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" true) | nindent 4 }}

    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["settings", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: SETTINGS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: SETTINGS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: SETTINGS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: SETTINGS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: SETTINGS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: SETTINGS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: SETTINGS_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: SETTINGS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: SETTINGS_HTTP_ADDR
              value: 0.0.0.0:9190
            - name: SETTINGS_GRPC_ADDR
              value: 0.0.0.0:9191
            - name: SETTINGS_DEBUG_ADDR
              value: 0.0.0.0:9194

            - name: STORAGE_GATEWAY_GRPC_ADDR
              value: {{ .appNameStorageSystem }}:9215
            - name: STORAGE_GRPC_ADDR
              value: {{ .appNameStorageSystem }}:9215

            {{- if not .Values.features.externalUserManagement.oidc.roleAssignment.enabled }}
            - name: SETTINGS_ADMIN_USER_ID
            {{- if .Values.features.externalUserManagement.enabled }}
              value: {{ .Values.features.externalUserManagement.adminUUID | quote }}
            {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.adminUserSecretRef }}
                  key: user-id
            {{- end }}
            {{- end }}

            {{- if or .Values.features.roles.customRoles .Values.features.roles.customRolesConfigRef }}
            - name: SETTINGS_BUNDLES_PATH
              value: /etc/ocis/custom-roles.json
            {{- end }}
            - name: SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: OCIS_SYSTEM_USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storagesystemSecretRef }}
                  key: api-key
            - name: OCIS_SYSTEM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.storagesystemSecretRef }}
                  key: user-id

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9190
            - name: grpc
              containerPort: 9191
            - name: metrics-debug
              containerPort: 9194

          {{- if or .Values.features.roles.customRoles .Values.features.roles.customRolesConfigRef }}
          volumeMounts:
            - name: ocis-role-config
              mountPath: /etc/ocis
          {{- end }}

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}

      {{- if .Values.features.roles.customRoles }}
      volumes:
        - name: ocis-role-config
          configMap:
            name: {{ .appName }}-role-config
      {{- end }}
      {{- if .Values.features.roles.customRolesConfigRef }}
      volumes:
        - name: ocis-role-config
          configMap:
            name: {{ .Values.features.roles.customRolesConfigRef }}
      {{- end }}
