{{- include "ocis.appNames" (dict "scope" . "appName" "appNameOcdav" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.ocdav.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["ocdav", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCDAV_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: OCDAV_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: OCDAV_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: OCDAV_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: OCDAV_HTTP_ADDR
              value: 0.0.0.0:8080
            - name: OCDAV_DEBUG_ADDR
              value: 0.0.0.0:9163

            - name: OCDAV_PUBLIC_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: {{ .appNameGateway }}:9142

            - name: OCDAV_INSECURE
              value: {{ .Values.insecure.ocisHttpApiInsecure | quote }}

            - name: OCDAV_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: OCDAV_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  key: machine-auth-api-key

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
            - name: metrics-debug
              containerPort: 9163
      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
