{{- include "ocis.appNames" (dict "scope" . "appName" "appNameGateway" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.gateway.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["gateway", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GATEWAY_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: GATEWAY_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: GATEWAY_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: GATEWAY_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: GATEWAY_GRPC_ADDR
              value: 0.0.0.0:9142
            - name: GATEWAY_DEBUG_ADDR
              value: 0.0.0.0:9143

            - name: REVA_GATEWAY
              # we also could have gateway:9142 here, but some
              # Kubernetes distributions as minikube do not support
              # resolving a container's hostname in the container.
              value: 127.0.0.1:9142

            - name: GATEWAY_FRONTEND_PUBLIC_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: GATEWAY_USERS_ENDPOINT
              value: {{ .appNameUsers }}:9144
            - name: GATEWAY_GROUPS_ENDPOINT
              value: {{ .appNameGroups }}:9160

            - name: GATEWAY_AUTH_BASIC_ENDPOINT
              value: {{ .appNameAuthBasic }}:9146
            - name: GATEWAY_AUTH_MACHINE_ENDPOINT
              value: {{ .appNameAuthMachine }}:9166

            - name: GATEWAY_PERMISSIONS_ENDPOINT
              value: {{ .appNameSettings }}:9191

            - name: GATEWAY_SHARING_ENDPOINT
              value: {{ .appNameSharing }}:9150
            - name: GATEWAY_STORAGE_PUBLIC_LINK_ENDPOINT
              value: {{ .appNameStoragePubliclink }}:9178
            - name: GATEWAY_STORAGE_USERS_ENDPOINT
              value: {{ .appNameStorageUsers }}:9157
            - name: GATEWAY_STORAGE_SHARES_ENDPOINT
              value: {{ .appNameStorageShares }}:9154

            - name: GATEWAY_APP_REGISTRY_ENDPOINT
              value: {{ .appNameAppRegistry }}:9242

            # cache
            - name: GATEWAY_CACHE_STORE
              value: {{ .Values.cache.type | quote }}
            {{- if ne .Values.cache.type "noop" }}
            - name: GATEWAY_CACHE_NODES
              value: {{ join "," .Values.cache.nodes | quote }}
            {{- end }}

            - name: GATEWAY_STORAGE_USERS_MOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configRefs.storageusersConfigRef }}
                  key: storage-uuid

            - name: GATEWAY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: STORAGE_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.transferSecretSecretRef }}
                  key: transfer-secret

          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-debug
            timeoutSeconds: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9142
            - name: metrics-debug
              containerPort: 9143

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
